### ISSUE TITLE
yeelink.bhf_light.v1不能调风向

### ISSUE THREAD

**Issue by yezivvvv** [al-one/hass-miio-yeelink#14]
型号：yeelink.bhf_light.v1
不能调风向
但是在添加集成的时候手动填入yeelink.bhf_light.v5，是可以调风向的，但就是风速不准确。

**Comment by al-one** [comment]
请更新至master分支新版版本。并自定义实体：
```yaml
# customize.yaml (配置 > 自定义 > 选择实体 > 添加 Other 属性)
fan.your_entity_id:
  support_oscillate: true
  support_direction: true
```

如果你不介意使用云端控制的话，可以使用[hass-xiaomi-miot](https://github.com/al-one/hass-xiaomi-miot)插件。
