### ISSUE TITLE
yeelink.bhf_light.v5 可以添加调节温度的功能吗

### ISSUE THREAD

**Issue by hustyep** [al-one/hass-miio-yeelink#16]
其他功能都很完美，就是目标温度这个，我通过send_command设置aim_temp没有生效，但是也没报错

**Comment by al-one** [comment]
```yaml
service: miio_yeelink.set_property
data:
  entity_id: light.yeelink_bhfv5_id
  field: aim_temp
  value: 30
```
