### ISSUE TITLE
 yeelink.light.fancl1 問題

### ISSUE THREAD

**Issue by oscarliuyc** [al-one/hass-miio-yeelink#18]
更新插件後， yeelink.light.fancl1 只能讀取狀態，不能開關燈和風扇。拜託看一看。

**Comment by al-one** [comment]
1. 开启插件debug
```yaml
service: logger.set_level
data:
  custom_components.miio_yeelink: debug
```
2. 操作实体后，获取相关[日志](https://my.home-assistant.io/redirect/logs)
