### ISSUE TITLE
Color temp for yeelink.light.color3 needs correction

### ISSUE THREAD

**Issue by mouth4war** [al-one/hass-miio-yeelink#20]
1700k-6500k
min_mireds: 153
max_mireds: 588

**Comment by al-one** [comment]
Is there any problem with this value ?

**Comment by al-one** [comment]
If you want to change them, you can add [custom attributes](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui) to the entity:
```yaml
# customize.yaml (Configuration > Customize > Select Entity > Add Other Attribute)
light.your_entity_id:
  support_color_temp: true
  min_color_temp: 1700
  max_color_temp: 6500
```
