### ISSUE TITLE
Yeelight Halo Ceiling Pro YLXD49YL, ceiling19

### ISSUE THREAD

**Issue by FalenDemon** [al-one/hass-miio-yeelink#6]
Hi there,
Nice to see some alternatives for HA besides yeelight integration (which one working bad on this model).

First of all, thanks for your work and this solution partially works with yeelink.light.ceiling19:
**Working:**
On\Off
Brightness

**Partially working**
Light temperature- it inverted (when I choose warm, it becomes cold)

**Not working**
Ambilight
Night mode
(can you add this? In yeelight integration it works)

**Comment by al-one** [comment]
The bug of color temperature fixed in version [v0.1.6](https://github.com/al-one/hass-miio-yeelink/releases/latest).

And you can use HA service to turn on the night mode like:
```yaml
service: miio_yeelink.send_command
data:
  entity_id: light.yeelight_entity_id
  method: set_ps
  params: ['nightlight','on']
```
Ambilight is not supported at present, But I think you can turn on it use HA service also.

**Comment by FalenDemon** [comment]
Thank you for quick reply, when I switch to night mode like you wrote i'll be able to control brightness?

**Comment by al-one** [comment]
```yaml
service: miio_yeelink.send_command
data:
  entity_id: light.yeelight_entity_id
  method: set_ps
  params: ['nightlight','on|99']
```
Switch to night mode and set brightness 99%.
