### ISSUE TITLE
浴霸灯能否控制夜灯模式

### ISSUE THREAD

**Issue by zhtengw** [al-one/hass-miio-yeelink#8]
您的插件有
```yaml
service: miio_yeelink.light_set_scene
data:
  entity_id: light.yeelight_entity_id
  scene: 3
```
或者[您提到的](https://github.com/al-one/hass-miio-yeelink/issues/6#issuecomment-758461551)
```yaml
service: miio_yeelink.send_command
data:
  entity_id: light.yeelight_entity_id
  method: set_ps
  params: ['nightlight','on']
```
来控制夜灯模式，但我的浴霸灯yeelink.bhf_light.v5用这两种方式都不生效，也没有错误提示，请问要如何控制浴霸灯的夜灯模式？

**Comment by al-one** [comment]
```yaml
service: miio_yeelink.send_command
data:
  entity_id: light.yeelight_entity_id
  method: set_ps
  params:
    - nighttime
    - enable  #开启夜灯
    # disable #关闭夜灯
```

**Comment by zhtengw** [comment]
> 
> 
> ```yaml
> service: miio_yeelink.send_command
> data:
>   entity_id: light.yeelight_entity_id
>   method: set_ps
>   params:
>     - nighttime
>     - enable  #开启夜灯
>     # disable #关闭夜灯
> ```

您好，这个也没有效果，在开发者工具里看到的状态属性是：
```
brightness: 255
model: yeelink.bhf_light.v5
lan_ip: 192.168.2.58
mac_address: '5C:E5:0C:A6:15:B2'
firmware_version: 2.1.3
hardware_version: esp32
entity_class: YeelightEntity
power: 'on'
nl_br: 7
delayoff: 0
bright: 100
friendly_name: 公卫浴霸灯
supported_features: 1
```

**Comment by al-one** [comment]
上面的命令是针对`yeelink.bhf_light.v2`的，至于v5你可以尝试下使用[MIHome mod](https://bbs.hassbian.com/forum.php?mod=redirect&goto=findpost&ptid=11276&pid=348919)操作设备后查看日志中的miio命令是多少。

**Comment by zhtengw** [comment]
我这里安装vevs的米家，在内部储存的vevs目录里只有automations、devices和translations三个空目录，没有logs目录，怎么操作设备都没有生成，smarthome目录下的logs目录内容又跟原版的米家没区别。

**Comment by al-one** [comment]
需要手动创建`/sdcard/vevs/logs/`目录

**Comment by zhtengw** [comment]
谢谢您，查看日志发现您之前说的命令是正确的，只是浴霸灯的夜灯模式不像吸顶灯一样是实时改变灯亮度的，发送命令只是改变了“在指定时间段开灯时显示夜灯亮度”的开关，所以我一直以为不成功。
我这里解释一下我的需求。我想要的是在HA中定义一些模板开关，用来切换灯具的夜灯模式，像米家吸顶灯这种，我的模板开关定义是：
```
living_room_nl:
  friendly_name: 客厅夜灯模式
  value_template: "{{ state_attr('light.ke_ting_xi_ding_deng', 'nl_br') != '0' }}"
  turn_on:
    service: miio_yeelink.send_command
    entity_id: light.ke_ting_xi_ding_deng
    data:
      method: set_ps
      params:
        - nightlight
        - 'on'
  turn_off:
    service: miio_yeelink.send_command
    entity_id: light.ke_ting_xi_ding_deng
    data:
      method: set_ps
      params:
        - nightlight
        - 'off'
  icon_template: >-
    {% if state_attr('light.ke_ting_xi_ding_deng', 'nl_br') != '0' %}
      mdi:weather-night
    {% else %}
      mdi:weather-sunny
    {% endif %}
```
而浴霸灯这个情况，就只能在turn_on，turn_off动作里再添加两个light.toggle来改变亮度了。
现在我遇到到问题是，正如[#7](https://github.com/al-one/hass-miio-yeelink/issues/7#issuecomment-762365311)中提到的，浴霸灯和风扇灯不像吸顶灯一样有个“nl_br”的状态属性来直接反映夜灯模式的开关，所以浴霸灯和风扇灯的夜灯模式模板开关的状态不知道如何确定。

**Comment by al-one** [comment]
您可以将`nl_br`添加到`BathHeaterEntityV5._props`尝试下
https://github.com/al-one/hass-miio-yeelink/blob/521e8636445839a379ea29c8346a1bc174828d6a/custom_components/miio_yeelink/__init__.py#L622-L623

如下：
```python
        self._props = ['power', 'bh_mode', 'fan_speed_idx', 'swing_action', 'swing_angle', 'bh_cfg_delayoff',
                       'bh_delayoff', 'light_cfg_delayoff', 'delayoff', 'aim_temp', 'nl_br']
```

**Comment by zhtengw** [comment]
> 
> 
> 针对浴霸(yeelink.bhf_light.v5)您可以将`nl_br`添加到`BathHeaterEntityV5._props`尝试下
在BathHeaterEntityV5._props添加了`nl_br`，效果跟之前没区别，不论什么模式，`nl_br`的值始终都是7。

风扇灯的话，不同模式下mode字段和nighttime字段都是不变的，`mode`始终为`null`，`nighttime`始终为0。
日光模式下风扇灯的状态属性：
```yaml
min_mireds: 175
max_mireds: 370
brightness: 255
color_temp: 175
model: yeelink.light.fancl5
lan_ip: 192.168.2.54
mac_address: '54:48:E6:72:C9:88'
firmware_version: 2.0.6_0006
hardware_version: esp32
entity_class: MiotLightEntity
power: true
mode: null
bright: 100
ct: 5714
flow: null
delayoff: 0
init_opt: 1
nighttime: 0
friendly_name: 餐厅灯
supported_features: 3
```
夜灯模式下风扇灯的状态属性：
```yaml
min_mireds: 175
max_mireds: 370
brightness: 13
color_temp: 175
model: yeelink.light.fancl5
lan_ip: 192.168.2.54
mac_address: '54:48:E6:72:C9:88'
firmware_version: 2.0.6_0006
hardware_version: esp32
entity_class: MiotLightEntity
power: true
mode: null
bright: 5
ct: 5714
flow: null
delayoff: 1
init_opt: 1
nighttime: 0
friendly_name: 餐厅灯
supported_features: 3
```
